name: context variable
on: push
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: first context variable
        run: echo "this is my first ${{toJson(github)}}"
      - name: shah variable background
        run: echo "$GITHUB_SHA"
