name: cicd practice

on: push

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout the code repo
     uses: actions/checkout@v4
   - name: configure aws credential
     uses: aws-actions/configure-aws-credentials@v6.1.0
     with:
       aws-access-key-id: ${{secrets.ACCESS_KEY_ID}}
       aws-secret-access-key: ${{secrets.ACCESS_KEY_SECRET}}
       aws-region: us-east-1
