name: cicd practice

on: 
   push:
     branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: myfirst step
        run: echo "my first step ${{vars.mykey}}"
 
  test:
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: test
        run: echo "this is test case ${{secrets.mykey_sec}}"
      
  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
    - name: deploy
      run: echo "this is deploy stage"
     
          
