name: ifcondition
on: 
 push:
   branches: main
 pull_request: 
  types: 
   - opened
   - synchronize
jobs:
  build:
   runs-on: ubuntu-latest
   if: github.event_name=='pull_request'
   steps:
    - name: build request
      run: echo "pull request is running"
  
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name=='push'
    steps:
      - name: push_reequest
        run: echo 'push request'
  
